task: instance
embed:
  _target_: hgcal_dev.training.criterion.CentroidInstanceLoss
  delta_v: 0.5
  delta_d: 1.5
  normalize: True
  use_weights: False
  cluster_ignore_label: ${dataset.cluster_ignore_label}
  semantic_ignore_label: ${dataset.semantic_ignore_label}