# @package _group_
task: instance
embed:
  _target_: hgcal_dev.training.criterion.CentroidInstanceLoss
  delta_v: 0.5
  delta_d: 1.5
  normalize: True
  use_weights: False
  ignore_semantic_label: ${dataset.ignore_label}