# @package _group_
task: panoptic
required_data: ${criterion.task}
alpha: 1.0
semantic:
  _target_: torch.nn.CrossEntropyLoss
  ignore_index: -1
embed:
  _target_: hgcal_dev.training.criterion.CentroidInstanceLoss
  delta_v: 0.5
  delta_d: 1.5
  normalize: True
  use_weights: False