# @package _group_
semantic:
  _target_: torch.nn.CrossEntropyLoss
  ignore_index: 255
embed:
  _target_: hgcal_dev.training.criterion.triplet_margin_loss_factory
  triplets_per_anchor: 1000
  p: 2
  normalize_embeddings: False