# @package _group_
task: instance
required_data: panoptic
embed:
  _target_: hgcal_dev.training.criterion.CentroidInstanceLoss
  delta_v: 0.5
  delta_d: 1.5
  normalize: True
  use_weights: False
  use_semantic: True
  semantic_ignore_index: 0