# @package _group_
_target_: hgcal_dev.datasets.hcal.HCalDataModule
seed: ${seed}
num_classes: 2
task: ${criterion.task}
data_dir: /home/alexj/data/hgcal-dev/hcal_3
raw_data_dir: /home/alexj/data/hgcal-dev/hcal_3/min_energy_0.0_min_hits_0
event_frac: 1.0
train_frac: 0.8
test_frac: 0.1
num_workers: 32
voxel_size: 10.0
num_epochs: ${train.num_epochs}
batch_size: ${train.batch_size}
num_features: 5
min_hits_per_cluster: 0
min_cluster_energy: 0.5
instance_label: truth
noise_id: -99
