# @package _group_
_target_: hgcal_dev.datasets.hcal.HCalDataModule
num_classes: 2
label_type: class_and_instance
data_dir: /home/alexjschuy/data/hcal
event_frac: 1.0
train_frac: 0.8
test_frac: 0.1
force_download: False
num_workers: 8
voxel_size: 10.0
num_epochs: ${train.num_epochs}
batch_size: ${train.batch_size}