# @package _group_
_target_: hgcal_dev.datasets.hcal.HCalDataModule
num_classes: 2
label_type: class
data_dir: /global/cscratch1/sd/schuya/hgcal-dev/data/hcal
num_events: 10000
num_train_events: 8000
num_test_events: 1000
force_download: False
num_workers: 8
voxel_size: 10.0
num_epochs: ${train.num_epochs}
batch_size: ${train.batch_size}