defaults:
  - base_dataset
_target_: hgcal_dev.datasets.hgcal.HGCalDataModule

# required fields:
num_classes: 4
num_features: 5
voxel_size: 0.05

# dataset-specific fields (should not change):

# data location (modify as needed):
data_dir: /home/alexj/data/hgcal-dev/hgcal
download: True

# config fields:
noise_level: 1.0
