defaults:
  - base_dataset
_target_: hgcal_dev.datasets.semantic_kitti.SemanticKITTIDataModule

# required fields:
num_classes: 19
num_features: 4
voxel_size: 0.05

# dataset-specific fields (should not change):
cluster_ignore_label: 255
semantic_ignore_label: 255

# data location (modify as needed):
root: /home/alexj/data/hgcal-dev/semantic_kitti/dataset/sequences

# config fields:
num_points: 80000