# @package _group_
_target_: hgcal_dev.datasets.simple.SimpleDataModule
seed: ${seed}
num_classes: 2
task: ${criterion.required_data}
data_dir: /home/alexj/data/hgcal-dev/simple
raw_data_dir: /home/alexj/data/hgcal-dev/simple
event_frac: 1.0
train_frac: 0.8
test_frac: 0.1
num_workers: 8
voxel_size: 0.1
num_epochs: ${train.num_epochs}
batch_size: ${train.batch_size}
num_features: 3