defaults:
  - base_dataset
_target_: hgcal_dev.datasets.simple.SimpleDataModule

# required fields:
num_classes: 2
num_features: 4
voxel_size: 0.05

# dataset-specific fields (should not change):

# data location (modify as needed):
data_dir: /home/alexj/data/hgcal-dev/simple

# config fields:
feats: ['x', 'y', 'z', 'E']
coords: ['x', 'y', 'z']