# @package _group_
_target_: hgcal_dev.datasets.vertex.VertexDataModule
num_classes: 2
task: ${criterion.task}
data_dir: /home/alexj/data/hgcal-dev/vertex
event_frac: 1.0
train_frac: 0.8
test_frac: 0.1
num_workers: 8
voxel_size: 0.5
num_epochs: ${train.num_epochs}
batch_size: ${train.batch_size}
num_features: 3