seed: 1588147245
deterministic: False
init_ckpt: null
log_level: DEBUG
defaults:
  - train: single_gpu
  - dataset: hgcal
  - metrics: semantic
  - optimizer: sgd
  - criterion: cross_entropy_loss
  - scheduler: lambda_lr
  - model: spvcnn
  - wandb: active
  - checkpoint: top_1
  
