outputs_dir: /home/alexj/outputs
predictions_dir: /home/alexj/predictions
hydra:
  run:
    dir: ${outputs_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 1588147245
deterministic: False
init_ckpt: null
overfit: False
log_level: INFO
defaults:
  - train: single_gpu
  - dataset: hcal
  - optimizer: adam
  - criterion: joint_centroid
  - scheduler: lambda_lr
  - model: spvcnn
  - wandb: upload
  - checkpoint: all
  - clusterer: hdbscan
  - swa: inactive