seed: 1588147245
deterministic: False
train:
  batch_size: 2
  num_epochs: 15

defaults:
  - dataset: hgcal
  - metrics: semantic
  - optimizer: sgd
  - criterion: cross_entropy_loss
  - scheduler: lambda_lr
  - model: spvcnn