output_dir: /global/cscratch1/sd/schuya/hgcal-dev/outputs
hydra:
  run:
    dir: ${output_dir}/hydra/${now:%Y-%m-%d}/${now:%H-%M-%S}
seed: 1588147245
deterministic: False
init_ckpt: null
log_level: INFO
defaults:
  - train: slurm
  - dataset: hcal
  - optimizer: sgd
  - criterion: joint
  - scheduler: lambda_lr
  - model: spvcnn
  - wandb: upload
  - checkpoint: top_1