seed: 1588147245
deterministic: False
init_ckpt: null
log_level: INFO
defaults:
  - train: single_gpu
  - dataset: hgcal
  - metrics: semantic
  - optimizer: sgd
  - criterion: joint
  - scheduler: lambda_lr
  - model: spvcnn
  - wandb: upload
  - checkpoint: top_1